image: martinlowinski/flutter-android-sdk

pipelines:
  default:
    - step:
        caches:
          - gradle
          - gradlewrapper
        script:
          - echo "Building APK..."
          - flutter doctor
          - flutter -v build apk

definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper