name: project_f
description: A new Flutter App

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: "^3.0.0"
  firebase_auth: "^0.5.0"
  # TODO add permission for IOS for image picker
  # https://pub.dartlang.org/packages/image_picker
  firebase_storage: "^0.2.1"
  flutter_facebook_login: "^1.1.0"
  cloud_firestore: "^0.5.0"
  firebase_core: "^0.1.0"
  flutter_staggered_grid_view: "^0.1.2"
  shared_preferences: "^0.4.0"
  cached_network_image: "^0.4.0-rc.1"
  image_picker: "^0.4.1"
  flutter_webview_plugin: ">=0.0.5 <0.1.0"
  instagram: "^1.0.0-rc.1"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
      - images/login.png
      - images/facebook.png
      - images/google_plus.png
      - images/instagram.png
      - images/box.png
      - images/box_image_1.png
      - images/box_image_2.png
      - images/box_image_3.png
      - images/girl.png
      - images/socks.png
      - images/sence.png
      - images/gus.png
      - images/postcard.png
      - images/notebook.png
      - images/socks_2.png
      - images/sammy_icon.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages